# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitversity < Formula
  desc ""
  homepage ""
  version "0.1.8"

  on_macos do
    on_intel do
      url "https://github.com/Babatunde50/gitversity-cli/releases/download/v0.1.8/gitversity-cli_Darwin_x86_64.tar.gz"
      sha256 "ad80daaaade1d11ef769493c7047dd2c79af0f48133d759bb880c6895d9a8919"

      def install
        bin.install "gitversity-cli"
        bin.install_symlink bin/"gitversity-cli" => "gitversity"
      end
    end
    on_arm do
      url "https://github.com/Babatunde50/gitversity-cli/releases/download/v0.1.8/gitversity-cli_Darwin_arm64.tar.gz"
      sha256 "e0a23bd20aae30a15db510b5618d718e65411cb4596945a36d28cad16a276786"

      def install
        bin.install "gitversity-cli"
        bin.install_symlink bin/"gitversity-cli" => "gitversity"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Babatunde50/gitversity-cli/releases/download/v0.1.8/gitversity-cli_Linux_x86_64.tar.gz"
        sha256 "6987336a4d219925e75a712d5b03fa94650931dbdfe2b6cde13e1ac61f9b9653"

        def install
          bin.install "gitversity-cli"
          bin.install_symlink bin/"gitversity-cli" => "gitversity"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Babatunde50/gitversity-cli/releases/download/v0.1.8/gitversity-cli_Linux_arm64.tar.gz"
        sha256 "b4969ecb59c27b0c90a74bc7bedcb031ed75003aaaaa70ad01807b132598c255"

        def install
          bin.install "gitversity-cli"
          bin.install_symlink bin/"gitversity-cli" => "gitversity"
        end
      end
    end
  end
end
