// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.2
// source: rpc_commit_repo.proto

package ggs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitToRepoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoId        string `protobuf:"bytes,1,opt,name=repoId,proto3" json:"repoId,omitempty"`
	CommitMessage string `protobuf:"bytes,2,opt,name=commitMessage,proto3" json:"commitMessage,omitempty"`
}

func (x *CommitToRepoRequest) Reset() {
	*x = CommitToRepoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_commit_repo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitToRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitToRepoRequest) ProtoMessage() {}

func (x *CommitToRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_commit_repo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitToRepoRequest.ProtoReflect.Descriptor instead.
func (*CommitToRepoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_commit_repo_proto_rawDescGZIP(), []int{0}
}

func (x *CommitToRepoRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *CommitToRepoRequest) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

type CommitToRepoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch       string   `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitHash   string   `protobuf:"bytes,2,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	Message      string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	FilesChanged int32    `protobuf:"varint,4,opt,name=filesChanged,proto3" json:"filesChanged,omitempty"`
	FilesCreated []string `protobuf:"bytes,5,rep,name=filesCreated,proto3" json:"filesCreated,omitempty"`
}

func (x *CommitToRepoResponse) Reset() {
	*x = CommitToRepoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_commit_repo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitToRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitToRepoResponse) ProtoMessage() {}

func (x *CommitToRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_commit_repo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitToRepoResponse.ProtoReflect.Descriptor instead.
func (*CommitToRepoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_commit_repo_proto_rawDescGZIP(), []int{1}
}

func (x *CommitToRepoResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CommitToRepoResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *CommitToRepoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitToRepoResponse) GetFilesChanged() int32 {
	if x != nil {
		return x.FilesChanged
	}
	return 0
}

func (x *CommitToRepoResponse) GetFilesCreated() []string {
	if x != nil {
		return x.FilesCreated
	}
	return nil
}

var File_rpc_commit_repo_proto protoreflect.FileDescriptor

var file_rpc_commit_repo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x70,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x67, 0x73, 0x22, 0x53, 0x0a, 0x13,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0xb0, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x6f, 0x52, 0x65,
	0x70, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x67, 0x69, 0x74, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x2f, 0x67, 0x69,
	0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x67, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_commit_repo_proto_rawDescOnce sync.Once
	file_rpc_commit_repo_proto_rawDescData = file_rpc_commit_repo_proto_rawDesc
)

func file_rpc_commit_repo_proto_rawDescGZIP() []byte {
	file_rpc_commit_repo_proto_rawDescOnce.Do(func() {
		file_rpc_commit_repo_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_commit_repo_proto_rawDescData)
	})
	return file_rpc_commit_repo_proto_rawDescData
}

var file_rpc_commit_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_commit_repo_proto_goTypes = []interface{}{
	(*CommitToRepoRequest)(nil),  // 0: ggs.CommitToRepoRequest
	(*CommitToRepoResponse)(nil), // 1: ggs.CommitToRepoResponse
}
var file_rpc_commit_repo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_commit_repo_proto_init() }
func file_rpc_commit_repo_proto_init() {
	if File_rpc_commit_repo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_commit_repo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitToRepoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_commit_repo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitToRepoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_commit_repo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_commit_repo_proto_goTypes,
		DependencyIndexes: file_rpc_commit_repo_proto_depIdxs,
		MessageInfos:      file_rpc_commit_repo_proto_msgTypes,
	}.Build()
	File_rpc_commit_repo_proto = out.File
	file_rpc_commit_repo_proto_rawDesc = nil
	file_rpc_commit_repo_proto_goTypes = nil
	file_rpc_commit_repo_proto_depIdxs = nil
}
